pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'Sentry'

include 'api'
include 'core:plugin'
include 'core:fabric'
include 'core:common'